api/urls.py
from django.urls import path, include
from api.views import *
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.authtoken import views

urlpatterns = [
    path('', PostList.as_view()),
    path('register', UserRegister.as_view()),
    path('account-list', AccountList.as_view()),
    path('user/<pk>', account_detail),
    path('settings',AccountSettings.as_view()),
    path('account/follows/<pk>', FollowsList.as_view()),
    path('follow/<pk>', FollowAccount.as_view()),
    path('account/followers/<pk>', FollowerList.as_view()),
    path('post/<pk>', PostDetail.as_view()),
    path('post/comments/<pk>', PostCommentList.as_view()),
    path('comment/<pk>', CommentDetail.as_view()),
    path('post/likes/<pk>', LikePostList.as_view()),
    path('trending/posts/<int:days>', trending_posts),
    path('trending/users', trending_accounts),
    path('search/<str:query>', search_accounts),
    path('notifications', NotificationList.as_view()),
    path('api-auth', include('rest_framework.urls')),
    #path('api-token-auth', views.obtain_auth_token)
]

urlpatterns = format_suffix_patterns(urlpatterns)

socialplatform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('messages/', include('chat.urls')),
    path('api/', include('api.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth import get_user_model
from datetime import datetime
from django.contrib.contenttypes.models import ContentType
from django.urls import reverse
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
import uuid

User = get_user_model()


class Account(models.Model):
    def __str__(self):
        return self.user.username

    def user_media_path(self, filename):
        return 'media/user_{0}/profile/{1}'.format(self.user.pk, filename)

    def get_absolute_url(self):
        return reverse("user", kwargs={'pk': self.pk})

    def check_follow(self, account_object):
        if Follow.objects.filter(follower=self, followed=account_object).exists():
            return True
        else:
            return False
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to=user_media_path, default='media/blank.png')
    name = models.CharField(max_length=100, default="")
    bio = models.TextField()
    followers = models.IntegerField(default=0)
    follows = models.IntegerField(default=0)


class Action(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    verb = models.CharField(max_length=100)
    date = models.DateTimeField(default=datetime.now())
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()
    content_user = models.ForeignKey(Account, related_name="content_user", on_delete=models.CASCADE)

    class Meta:
        ordering = ('-date',)


class Post(models.Model):
    def __str__(self):
        return "post by " + self.owner.user.username

    def post_media_path(self, filename):
        return 'media/user_{0}/posts/{1}'.format(self.owner.pk, filename)

    def get_absolute_url(self):
        return reverse('post', kwargs={'pk': self.pk})
        # return "/post/%i" % self.pk

    def get_newest_comment(self):
        if Comment.objects.filter(post=self).exists():
            comment = Comment.objects.filter(post=self).order_by('-date').first()
            return comment

    owner = models.ForeignKey(Account, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to=post_media_path)
    description = models.TextField()
    date = models.DateTimeField(default=datetime.now())
    edit_date = models.DateTimeField(default=datetime.now())
    no_of_likes = models.IntegerField(default=0)
    newest_comment = get_newest_comment
    action = GenericRelation(Action, related_query_name='post')

    class Meta:
        ordering = ('-date',)


class LikePost(models.Model):
    def __str__(self):
        return "post by " + self.post.owner.user.username

    def get_absolute_url(self):
        return self.post.get_absolute_url()

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    date = models.DateTimeField(default=datetime.now())
    action = GenericRelation(Action, related_query_name='like')


class Follow(models.Model):
    def __str__(self):
        return self.followed.user.username

    def get_absolute_url(self):
        return reverse("user", kwargs={'pk': self.followed.pk})

    follower = models.ForeignKey(Account, related_name="follower", on_delete=models.CASCADE)
    followed = models.ForeignKey(Account, related_name="followed", on_delete=models.CASCADE)
    date = models.DateTimeField(default=datetime.now())
    action = GenericRelation(Action, related_query_name='follow')


class Comment(models.Model):
    def get_absolute_url(self):
        return reverse("post", kwargs={'pk': self.post.pk})
        # return "/post/%i" % self.post.pk

    def __str__(self):
        return "post by " + self.post.owner.user.username

    owner = models.ForeignKey(Account, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.TextField()
    date = models.DateTimeField(default=datetime.now())
    action = GenericRelation(Action, related_query_name='comment')
    edit_date = models.DateTimeField(default=datetime.now())

    class Meta:
        ordering = ('-date',)

templates/add_post_form.html
{% extends 'form_template.html' %}
{% block form %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        Image:
        <input class='form-control' type="file" name="picture" accept="image/*" required="" id="id_picture">
        Description:
        <textarea class="form-control" name="description" cols="40" rows="10" required="" id="id_description"></textarea>
        <br>
        <button class="btn btn-primary d-block w-100" type="submit">Save</button>
    </form>
{% endblock %}

templates/base.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>social</title>
    <link rel="stylesheet" href="{%static 'bootstrap/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&amp;display=swap">
    <link rel="stylesheet" href="{%static 'css/Banner-Heading-Image-images.css'%}">
    <link href="{%static 'css/fontawesome.css'%}" rel="stylesheet">
    <link href="{%static 'css/brands.css'%}" rel="stylesheet">
    <link href="{%static 'css/solid.css'%}" rel="stylesheet">

</head>

<body>
    <nav class="navbar navbar-light navbar-expand-md sticky-top navbar-shrink py-3" id="mainNav">
        <div class="container"><a class="navbar-brand d-flex align-items-center" href="/">
                        <path fill-rule="evenodd" d="M0 10.5A1.5 1.5 0 0 1 1.5 9h1A1.5 1.5 0 0 1 4 10.5v1A1.5 1.5 0 0 1 2.5 13h-1A1.5 1.5 0 0 1 0 11.5v-1zm1.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zm10.5.5A1.5 1.5 0 0 1 13.5 9h1a1.5 1.5 0 0 1 1.5 1.5v1a1.5 1.5 0 0 1-1.5 1.5h-1a1.5 1.5 0 0 1-1.5-1.5v-1zm1.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zM6 4.5A1.5 1.5 0 0 1 7.5 3h1A1.5 1.5 0 0 1 10 4.5v1A1.5 1.5 0 0 1 8.5 7h-1A1.5 1.5 0 0 1 6 5.5v-1zM7.5 4a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1z"></path>
                        <path d="M6 4.5H1.866a1 1 0 1 0 0 1h2.668A6.517 6.517 0 0 0 1.814 9H2.5c.123 0 .244.015.358.043a5.517 5.517 0 0 1 3.185-3.185A1.503 1.503 0 0 1 6 5.5v-1zm3.957 1.358A1.5 1.5 0 0 0 10 5.5v-1h4.134a1 1 0 1 1 0 1h-2.668a6.517 6.517 0 0 1 2.72 3.5H13.5c-.123 0-.243.015-.358.043a5.517 5.517 0 0 0-3.185-3.185z"></path>
                    <span>Social</span></a><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="navbar-nav mx-auto">
                    <li class="nav-item"><a class="nav-link" href="{% url 'search' %}">search</a></li>
                    {%if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="">message</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'user' user.account.pk %}">@{{ user.username }}</a></li>
                    </ul>
                        <a class="btn btn-primary shadow" role="button" href="{%url 'post-create'%}">Add new post</a>
                        <a style="margin-left: 1em" href="{% url 'logout' %}"><i class="fa fa-sign-out"></i></a>
                {%else%}
                </ul><a class="btn btn-primary shadow" role="button" href="{% url 'login' %}">Login</a>
                {%endif%}
            </div>
        </div>
    </nav>
    {%block main%}

    {%endblock%}
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

    <script src="{%static 'js/jquery.min.js'%}"></script>
    <script src="{%static 'bootstrap/js/bootstrap.min.js'%}"></script>
    <script src="{%static 'js/bold-and-bright.js'%}"></script>
</body>

</html>

templates/change_password.html
{% extends 'form_template.html' %}
{% block form %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        Old password:
        <input class='form-control' type="password" name="old_password">
            {% if form.errors.old_password %}
             {{ form.errors.old_password }}
            {% endif %}
        New password:
        <input class='form-control' type="password" name="new_password1">
            {% if form.errors.new_password1 %}
             {{ form.errors.new_password1 }}
            {% endif %}
        Confirm new password:
        <input class='form-control' type="password" name="new_password2">
        {% if form.errors.new_password2 %}
         {{ form.errors.new_password2 }}
        {% endif %}
        <br>
        <button class="btn btn-primary d-block w-100" type="submit">Change Password</button>
    </form>
{% endblock %}

templates/edit_comment_form.html
{% extends 'form_template.html' %}
{% block form %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        Comment:
        <textarea class="form-control" name="comment" cols="40" rows="10" required="" id="id_description">{{ comment.comment }}</textarea>
        <br>
        <input class="btn btn-primary d-block w-100" value="Save" type="submit">
    </form>
{% endblock %}

templates/form_login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block main %}
    <section class="position-relative py-4 py-xl-5">
        <div class="container">
            <div class="row mb-5">
                <div class="col-md-8 col-xl-6 text-center mx-auto">
                    <h2>{{ title }}</h2>
                </div>
            </div>
            <div class="row d-flex justify-content-center">
                <div class="col-md-6 col-xl-4">
                    <div class="card mb-5">
                        <div class="card-body d-flex flex-column align-items-center">
                            <div class="bs-icon-xl bs-icon-circle bs-icon-primary bs-icon my-4"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-person">
                                    <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"></path>
                                </svg></div>
                            <form class="text-center" method="post">
                                {%  csrf_token %}
                                <input class="form-control mb-4" type="text" name="username" placeholder="username">
                                <input class="form-control mb-4" type="password" name="password" placeholder="password">
                                <br>
                                <br>
                                <div class="mb-3"><button class="btn btn-primary d-block w-100" type="submit">{{ title }}</button></div>
                            </form>
                            {% if title == "Login" %}
                                <a class="text-muted" href="register">Register</a>
                            {% endif %}
                            {% if title == "Register" %}
                                <a class="text-muted" href="login">Login</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/form_template.html
{% extends 'base.html' %}
{% block main %}
    <section class="bg-primary-gradient">
            <div class="container pt-4 pt-xl-5" style="width: 500px;height: 500px;">
                <div class="row pt-5">
                    <h2 class="text-center mb-4">{{title}}</h2>
                    {% block form %}

                    {% endblock %}
                </div>
            </div>
        </section>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block main %}
    <section class="bg-primary-gradient">
            <div class="container pt-4 pt-xl-5" style="width: 500px;height: 500px;">
                {% for post in posts %}
                    <div class="row pt-5">
                        <div class="col-md-12" style="padding-bottom: 1em"><img class="w-100 h-100 fit-cover" src="{{post.picture.url}}"></div>
                            <div class="col-md-10 col-xl-10"><strong><a href="{% url 'user' post.owner.pk %}"><img style="width: 30px; height: 30px;  border-radius: 50%;" src="{{ post.owner.profile_picture.url }}">@{{ post.owner.user }}</a> <p style="font-size:90%;">{{ post.no_of_likes }} likes</p></strong>
                                <p style="font-size:70%; margin-top: -1em">{{ post.date }}</p>
                                <p><a href="{% url 'post' post.pk %}" style="text-decoration: none"> {{ post.description }}</a></p>
                            </div>
                        <div class="col-md-2 col-xl-2">
                            <a href="{% url 'like' post.pk %}"><i class="fa fa-heart"></i></a>
                            <div>
                                {% if user == post.owner.user %}
                                    <a href="{% url 'post-update' post.pk %}"><i class='far fa-edit'></i></a>
                                    <br>
                                    <a href="{% url 'post-delete' post.pk %}"><i class='far fa-trash'></i></a>
                                {% endif %}
                            </div>
                        </div>
                    </div>

                    <div style="padding-left: 2em">
                            {% if post.newest_comment %}
                                <a class="container pt-4 pt-xl-5" style="margin-left: 30%;width:70%; font-size: 0.8em">
                                    <a style="font-size: 0.8em; text-decoration: none" href="{% url 'user' post.newest_comment.owner.pk %}"><p><img style="width: 30px;height: 30px; border-radius: 50%;" src="{{ post.newest_comment.owner.profile_picture.url }}">{{ post.newest_comment.owner.user }} {{ post.newest_comment.date }}</p></a>
                                    <p style="padding-left:1em">{{ post.newest_comment.comment }}</p>
                                    {% if user == post.newest_comment.owner.user %}
                                        <div style="padding-left:1em">
                                            <a href="{% url 'comment-update' post.newest_comment.pk %}?next={% url 'post' post.pk %}"><i class='far fa-edit'></i></a>
                                            <a href="{% url 'comment-delete' post.newest_comment.pk %}"><i class='far fa-trash'></i></a>
                                        </div>
                                        </a>
                                    {% endif %}
                            {% endif %}
                    </div>
                        <br>
                    {% endfor %}
                    <div class="pagination">
                        <span class="step-links" style="text-align: center;">
                            {% if posts.has_previous %}
                                <a href="?page={{ posts.previous_page_number }}">less</a>
                            {% endif %}
                            {% if posts.has_next %}
                                <a href="?page={{ posts.next_page_number }}">more</a>
                            {% endif %}
                        </span>
                    </div>
            </div>
    </section>

{% endblock %}

templates/post_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block main %}
    <section class="bg-primary-gradient">
            <div class="container pt-4 pt-xl-5" style="width: 500px;height: 500px;">
                <div class="row pt-5">
                    <div class="col-md-12" style="padding-bottom: 1em"><img class="w-100 h-100 fit-cover" src="{{post.picture.url}}"></div>
                    <div class="col-md-10 col-xl-10"><strong><a href="{% url 'user' post.owner.pk %}"><img style="max-width: 30px; border-radius: 50%;" src="{{ post.owner.profile_picture.url }}">@{{ post.owner.user }}</a> <p style="font-size:90%;">{{ post.no_of_likes }} likes</p></strong>
                        <p style="font-size:70%; margin-top: -1em">{{ post.date }}</p>
                        <p><a href="{% url 'post' post.pk %}" style="text-decoration: none"> {{ post.description }}</a></p>
                    </div>
                    <div class="col-md-2 col-xl-2">
                        <a href="{% url 'like' post.pk %}"><i class="fa fa-heart"></i></a>
                        <div>
                            {% if user == post.owner.user %}
                                <a href="{% url 'post-update' post.pk %}"><i class='far fa-edit'></i></a>
                                <br>
                                <a href="{% url 'post-delete' post.pk %}"><i class='far fa-trash'></i></a>
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-md-12 justify-content-center">
                    {% if user.is_authenticated %}
                    Add new comment
                        <form action="{% url 'add-comment' post.pk %}" method="post">
                            {% csrf_token %}
                            <textarea class="form-control" name="comment" cols="10" rows="2" required=""></textarea>
                            <br>
                            <button class="btn btn-primary d-block w-20" type="submit">Add comment</button>
                        </form>
                    {% endif %}
                    {% if comments %}
                    Comments:
                        {% for comment in comments %}
                            <div>
                            <a class="container pt-4 pt-xl-5" style="margin-left:1em; font-size: 0.8em">
                                <a style="font-size: 0.8em; text-decoration: none" href="{% url 'user' comment.owner.pk %}"><p><img style="width: 30px; border-radius: 50%;" src="{{ comment.owner.profile_picture.url }}">{{ comment.owner.user }} {{ comment.date }}</p></a>
                                <p style="padding-left:1em">{{ comment.comment }}</p>
                                {% if user == comment.owner.user %}
                                    <div style="padding-left:1em">
                                        <a href="{% url 'comment-update' comment.pk %}"><i class='far fa-edit'></i></a>
                                        <a href="{% url 'comment-delete' comment.pk %}"><i class='far fa-trash'></i></a>
                                    </div>
                                    </a>
                                {% endif %}
                            </div>
                        {% endfor %}
                    {% endif %}
                    </div>
                </div>
            <br>
            <div class="pagination justify-content-center">
                <span class="step-links" style="text-align: center;">
                    {% if comments.has_previous %}
                        <a href="?page={{ comments.previous_page_number }}">newer comments</a>
                    {% endif %}
                    {% if comments.has_next %}
                        <a href="?page={{ comments.next_page_number }}">older comments</a>
                    {% endif %}
                </span>
            </div>
            </div>
        </section>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% block main %}
<section class="bg-primary-gradient">
    <div class="container pt-4 pt-xl-5" style="width: 500px;height: 500px;">
        <div class="row pt-5">
            <form class="text-center" method="post">
                {% csrf_token %}
                <div class="mb-3"><input class="form-control" type="text" name="search"></div>
                <div class="mb-3"><button class="btn btn-primary d-block w-100" type="submit">Search</button></div>
            </form>
            <div class="row pt-5">
                {% if results %}
                    {% for result in results %}
                        <strong class="text-decoration-none" style="padding-bottom: 1em"><img style="width:100px; height: 100px; border-radius: 50%; margin-right: 1em" src="{{ result.profile_picture.url}}"><a href="{% url 'user' result.pk %}">@{{ result.user }}</a></strong>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="row pt-5">
                {% if popular_users %}
                    {% for result in popular_users %}
                        <div class="col-3 text-center">
                            <a href="{% url 'user' result.pk %}" style="padding-bottom: 1em">
                            <img style="width:100px; height: 100px; border-radius: 50%; margin-right: 1em" src="{{ result.profile_picture.url}}">
                            <strong class="text-center text-decoration-none">@{{ result.user }}</strong>
                            </a>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="row pt-5">
                {% if popular_posts %}
                    <div class="col">
                        {% for post in popular_posts %}
                            <div class="col-md-12" style="padding-bottom: 1em"><img class="w-100 h-100 fit-cover" src="{{post.picture.url}}"></div>
                            <div class="row">
                                <div class="col-md-10 col-xl-10"><strong><a href="{% url 'user' post.owner.pk %}"><img style="width: 30px; height: 30px; border-radius: 50%;" src="{{ post.owner.profile_picture.url }}">@{{ post.owner.user }}</a> <p style="font-size:90%;">{{ post.no_of_likes }} likes</p></strong>
                                    <p style="font-size:70%; margin-top: -1em">{{ post.date }}</p>
                                    <p><a href="{% url 'post' post.pk %}" style="text-decoration: none"> {{ post.description|truncatewords:20 }}</a></p>
                                </div>
                                <div class="col-md-2 col-xl-2">
                                    <a href="{% url 'like' post.pk %}"><i class="fa fa-heart"></i></a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="pagination">
                        <span class="step-links" style="text-align: center;">
                            {% if popular_posts.has_previous %}
                            <a href="?page={{ popular_posts.previous_page_number }}">less</a>
                         {% endif %}
                         {% if popular_posts.has_next %}
                             <a href="?page={{ popular_posts.next_page_number }}">more</a>
                         {% endif %}
                        </span>
                {% endif %}
            </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/settings.html
{% extends 'base.html' %}
{% block main %}
        <div class="container d-flex flex-column align-items-center py-4 py-xl-5">
            <div class="row gy-4 w-100" style="max-width: 800px;">
            <div class="col-md-3">
                    <img style="width: 150px;height: 150px; border-radius: 50%;" src="{{ account.profile_picture.url }}">
                </div>
                <div class="col-md-2 text-center d-flex d-md-flex flex-row justify-content-md-start align-items-md-center">
                    <strong><a class="text-decoration-none" href="{% url 'user' account.pk %}">@{{ account.user }}</a></strong>
                </div>
                <div class="col-md-2 text-center d-flex d-md-flex flex-row justify-content-md-start align-items-md-center">
                    <strong><a href="{% url 'followers' account.pk %}">Followers: {{ account.followers }}</a></strong>
                </div>
                <div class="col-md-2 text-center d-flex d-md-flex flex-row justify-content-md-start align-items-md-center">
                    <strong><a href="{% url 'follows' account.pk %}">Follows: {{ account.follows }}</a></strong>
                </div>
                <div class="col text-center d-md-flex justify-content-md-center align-items-md-center"><a class="btn btn-primary btn-sm d-flex d-md-flex flex-row justify-content-center align-items-center flex-wrap justify-content-md-center align-items-md-center" href="{% url 'account-update'  %}">Edit account info</a></div>
            </div>
        </div>
    <div class="row">
        <div class="col-md-6">
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 d-md-flex justify-content-md-center align-items-md-center">
            <p></p><a href="{% url 'account-delete' %}" class="btn btn-danger btn-sm d-flex d-md-flex flex-row justify-content-center align-items-center flex-wrap justify-content-md-center align-items-md-center" type="button">Delete Account</a>
        </div>
        <div class="col-md-6 text-center d-md-flex justify-content-md-center align-items-md-center"><a href="{% url 'change-password' %}" class="btn btn-primary btn-sm d-flex d-md-flex flex-row justify-content-center align-items-center flex-wrap justify-content-md-center align-items-md-center" type="button">Change password</a></div>
    </div>
    <div class="container" style="padding-left: 3em">
        <br>
        Recent actions:
            {% for action in actions %}
            <div class="col-md-6 d-md-flex" style="padding-left: 1em">
                <strong><a href="{% url 'user' action.user.pk %}">@{{action.user.user.username}}</a> {{ action.verb }} <a href="{{ action.content_object.get_absolute_url }}">{{ action.content_object }}</a></strong>
            </div>
            {% endfor %}
        <div class="pagination">
                <span class="step-links" style="text-align: center;">
                    {% if actions.has_previous %}
                        <a href="?page={{ actions.previous_page_number }}">newer</a>
                    {% endif %}
                    {% if actions.has_next %}
                        <a href="?page={{ actions.next_page_number }}">older</a>
                    {% endif %}
                </span>
            </div>
        </div>
        </div>
        <br>
</section>
{% endblock %}

templates/user_followers.html
{% extends 'user_template.html' %}
{% block user_data %}
    {% for follower in followers %}
        <div class="container" style="margin-top: 1em;width: 50%;">
            <div class="row text-center">
                <div class="col-10 col-md-6">
                    <div class="row">
                        <div class="col-6">
                            <img style="width: 100px;height: 100px; border-radius: 50%;" src="{{ follower.follower.profile_picture.url }}">
                        </div>
                        <div class="col-6 text-justify align-self-center">
                            <strong><a href="{% url 'user' follower.follower.pk %}">@{{ follower.follower }}</a></strong>
                        </div>
                        </div>
                </div>
                <div class="col-3 col-md-6 text-right align-self-center">
                    {% if user == follower.follower.user %}
                            <a class="btn btn-primary btn-sm d-flex d-md-flex flex-row justify-content-center align-items-center flex-wrap justify-content-md-center align-items-md-center" href="{% url 'settings' %}">Settings</a>
                        {% else %}
                            <a class="btn btn-primary btn-sm d-flex d-md-flex flex-row justify-content-center align-items-center flex-wrap justify-content-md-center align-items-md-center" href="{% url 'follow' account.pk %}">Follow</a>
                        {% endif %}
                </div>
        </div>
    {% endfor %}
    <div class="pagination">
        <span class="step-links" style="text-align: center;">
            {% if followers.has_previous %}
                <a href="?page={{ followers.previous_page_number }}">newer</a>
            {% endif %}
            {% if followers.has_next %}
                <a href="?page={{ followers.next_page_number }}">older</a>
            {% endif %}
        </span>
    </div>
{% endblock %}